using System.Collections.Generic;

/// <summary>
/// Interface for anything that participates in the power network.
/// Nodes can generate power, consume power, or both.
/// </summary>
public interface IPowerNode
{
    /// <summary>
    /// Unique identifier for this node.
    /// </summary>
    string NodeId { get; }

    /// <summary>
    /// Watts generated by this node. Zero for pure consumers.
    /// </summary>
    float PowerGeneration { get; }

    /// <summary>
    /// Watts consumed by this node. Zero for pure generators.
    /// </summary>
    float PowerConsumption { get; }

    /// <summary>
    /// Returns the adjacent nodes in the power graph that this node is connected to.
    /// </summary>
    IReadOnlyList<IPowerNode> GetConnectedNodes();
}
